"use client";
import Image from "next/image";
import Link from "next/link";
import {useMemo,useState} from "react";
import {occasionSlug,type Occasion} from "@/lib/occasions-content";
import {outfitSlug,type Outfit} from "@/lib/outfits-content";
import styles from "@/app/occasions/[slug]/occasion-detail.module.css";

type SortMode="new"|"saving"|"cheap";
const inr=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
const dateFmt=new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"});
function saving(outfit:Outfit){return Math.round((1-outfit.swap/outfit.worn)*100);}

export function OccasionDetail({occasion,outfits,related}:{occasion:Occasion;outfits:Outfit[];related:Occasion[]}){
  const [eventDate,setEventDate]=useState("2026-11-21");const [budget,setBudget]=useState<number|null>(null);const [sort,setSort]=useState<SortMode>("new");const [saved,setSaved]=useState<number[]>([]);
  const verdict=useMemo(()=>deliveryVerdict(eventDate),[eventDate]);
  const results=useMemo(()=>outfits.filter((outfit)=>!budget||outfit.swap<=budget).sort((a,b)=>sort==="saving"?(b.worn-b.swap)-(a.worn-a.swap):sort==="cheap"?a.swap-b.swap:b.date.localeCompare(a.date)),[budget,outfits,sort]);
  const averageSaving=Math.round((1-occasion.averageSwap/occasion.averageWorn)*100);
  return <main className={styles.page}>
    <header className={styles.hero}><Image src={`https://picsum.photos/seed/cpocc${occasion.id}/1600/700`} alt="" fill priority sizes="100vw"/><div className={styles.overlay}/><div className={styles.shell}><nav><Link href="/">Home</Link><i>›</i><Link href="/occasions">Occasions</Link><i>›</i><span>{occasion.name}</span></nav><h1>{occasion.name}</h1><p>{occasion.description} {occasion.looks} celebrity looks decoded piece by piece — and what each costs without the designer price.</p><div className={styles.heroStats}><div><b>{occasion.looks}</b><span>Looks decoded</span></div><div><b>{inr.format(occasion.averageWorn)}</b><span>Avg as worn</span></div><div><b>{inr.format(occasion.averageSwap)}</b><span>Avg swap</span></div><div><b>{inr.format(occasion.swapFrom)}</b><span>Cheapest look</span></div></div></div></header>
    <div className={styles.shell}>
      <section className={styles.calculator}><div><h2>When&apos;s the {occasion.name.toLowerCase()}?</h2><p>Indian delivery runs 4–9 days, and you&apos;ll want time to try it on and swap sizes. Tell us the date and we&apos;ll calculate your real deadline.</p></div><div className={styles.dateForm}><label>Event date<input type="date" value={eventDate} onChange={(event)=>setEventDate(event.target.value)}/></label></div><div className={`${styles.verdict} ${styles[verdict.tone]}`}><strong>{verdict.title}</strong><p>{verdict.body}</p><div><span>Event in<b>{verdict.days} days</b></span><span>Order by<b>{verdict.orderBy}</b></span><span>Typical delivery<b>4–9 days</b></span></div></div></section>
      <section className={styles.section}><SectionHeading eyebrow="The guide" title={`What to actually wear to a ${occasion.name.toLowerCase()}`}/><div className={styles.guide}><p>{occasion.description} The best version is the one that works for the event itself, not only for the photograph.</p><p>Across the {occasion.looks} looks in this archive, <b>{occasion.garments[0].name.toLowerCase()}</b> appears most often. The successful versions concentrate detail where it reads clearly and keep the rest of the styling controlled.</p><blockquote>If you take one thing from this page: <b>choose the outfit for how the event feels and moves, not only for the first photo.</b></blockquote><p>One statement accessory is usually enough. Repeating every jewellery cue from a celebrity look makes the affordable version feel busier, not richer.</p><p>The dupe economics are strong: the average saving across this archive is <b>{averageSaving}%</b>, with complete looks beginning at {inr.format(occasion.swapFrom)}.</p><small>Written by <b>Rabi</b> · Based on {occasion.looks} decoded looks · Prices re-checked 25 Aug 2026</small></div></section>
      <section className={styles.section}><SectionHeading eyebrow="The pattern" title={`What ${occasion.looks} ${occasion.name.toLowerCase()} looks have in common`} body="Counted across the archive — not an impression, the actual tally."/><div className={styles.patternGrid}><div className={styles.bars}><h3>Garment worn</h3>{occasion.garments.map((garment)=><div key={garment.name}><p><span>{garment.name}</span><b>{garment.count} looks · {Math.round(garment.count/occasion.looks*100)}%</b></p><i><b style={{width:`${garment.count/occasion.garments[0].count*100}%`}}/></i></div>)}</div><div className={styles.panel}><section><h3>Colours that dominate</h3><div className={styles.palette}>{occasion.colours.map((colour)=><span key={colour.name}><i style={{background:colour.value}}/><small>{colour.name}</small></span>)}</div></section><section><h3>Most repeated labels</h3><p className={styles.tags}><span>Sabyasachi</span><span>Anita Dongre</span><span>Manish Malhotra</span><span>Raw Mango</span></p></section><section><h3>Where the swaps come from</h3><p className={styles.tags}><span>Libas</span><span>Myntra</span><span>Ajio</span><span>Nykaa Fashion</span><span>Westside</span></p></section></div></div></section>
      <section className={styles.section}><SectionHeading eyebrow="By budget" title={`What a ${occasion.name.toLowerCase()} look costs`} body="Complete looks grouped by what you'd actually spend."/><div className={styles.budgetBands}>{[2500,5000,10000].map((cap,index)=><article key={cap}><p>Complete look under</p><h3>{inr.format(cap)}</h3><span>{[9,24,18][index]} looks in this band</span><ul><li>Main outfit <b>{inr.format(Math.round(cap*.58))}</b></li><li>Statement accessory <b>{inr.format(Math.round(cap*.18))}</b></li><li>Shoes <b>{inr.format(Math.round(cap*.15))}</b></li><li>Bag or finishing piece <b>{inr.format(Math.round(cap*.09))}</b></li></ul><button type="button" onClick={()=>setBudget(cap)}>See looks →</button></article>)}</div></section>
      <section className={styles.section}><SectionHeading eyebrow="The archive" title={`All ${occasion.looks} ${occasion.name.toLowerCase()} looks`}/><div className={styles.archiveBar}><div>{[null,2500,5000,10000].map((cap)=><button type="button" aria-pressed={budget===cap} onClick={()=>setBudget(cap)} key={cap??"all"}>{cap?`Under ${inr.format(cap)}`:"All"}</button>)}</div><select value={sort} onChange={(event)=>setSort(event.target.value as SortMode)}><option value="new">Newest</option><option value="saving">Biggest saving</option><option value="cheap">Cheapest swap</option></select></div>{results.length?<div className={styles.grid}>{results.map((outfit)=><OutfitCard outfit={outfit} saved={saved.includes(outfit.id)} onSave={()=>setSaved(saved.includes(outfit.id)?saved.filter((id)=>id!==outfit.id):[...saved,outfit.id])} key={outfit.id}/>)}</div>:<div className={styles.empty}><h3>No loaded looks in this slice yet</h3><p>The archive totals are ready for CMS import. Current local outfit records will appear here automatically.</p>{budget&&<button type="button" onClick={()=>setBudget(null)}>Show all</button>}</div>}</section>
      <section className={`${styles.section} ${styles.faq}`}><SectionHeading eyebrow="Asked a lot" title={`${occasion.name} questions`}/><details open><summary>What should a guest wear?</summary><p>Start with {occasion.garments[0].name.toLowerCase()} or {occasion.garments[1].name.toLowerCase()}, then tune the fabric weight and jewellery to the time of day and how much movement the event involves.</p></details><details><summary>How much should the complete outfit cost?</summary><p>The celebrity looks average {inr.format(occasion.averageWorn)}, while the swaps average {inr.format(occasion.averageSwap)}. A convincing complete look can start around {inr.format(occasion.swapFrom)}.</p></details><details><summary>Which colours work best?</summary><p>{occasion.colours.map((colour)=>colour.name).join(", ")} recur most often across the archive. Use one as the dominant colour and keep accessories quieter.</p></details><details><summary>How early should I order?</summary><p>Three weeks is comfortable. Two weeks is tight but workable. Inside ten days, prioritize in-stock items with express delivery.</p></details></section>
      <section className={styles.related}><SectionHeading eyebrow="Nearby" title={`Other ${occasion.group.toLowerCase()} occasions`}/><div>{related.map((item)=><Link href={`/occasions/${occasionSlug(item)}`} key={item.id}><Image src={`https://picsum.photos/seed/cpocc${item.id}/600/400`} alt="" fill sizes="(max-width:1023px) 50vw, 25vw"/><span><b>{item.name}</b><small>{item.looks} looks · from {inr.format(item.swapFrom)}</small></span></Link>)}</div></section>
    </div>
  </main>;
}

function deliveryVerdict(value:string){const now=new Date("2026-08-28T00:00:00");const event=new Date(`${value}T00:00:00`);const days=Math.round((event.getTime()-now.getTime())/86400000);const order=new Date(event.getTime()-14*86400000);const orderBy=Number.isNaN(order.getTime())?"Choose a date":dateFmt.format(order);if(days<0)return{tone:"bad",title:"That date has passed",body:"Pick a future date and we'll work backwards from it.",days:0,orderBy};if(days>=28)return{tone:"ok",title:"You have plenty of time",body:`Order by ${orderBy} and you'll have room to try things on and exchange a size.`,days,orderBy};if(days>=14)return{tone:"warn",title:"Getting tight — order this week",body:"You have delivery time, but limited room for a size exchange.",days,orderBy};return{tone:"bad",title:"Express delivery or local shopping",body:"You are inside the comfortable online-ordering window.",days:Math.max(days,0),orderBy};}
function SectionHeading({eyebrow,title,body}:{eyebrow:string;title:string;body?:string}){return <div className={styles.sectionHeading}><p>{eyebrow}</p><h2>{title}</h2>{body&&<span>{body}</span>}</div>;}
function OutfitCard({outfit,saved,onSave}:{outfit:Outfit;saved:boolean;onSave:()=>void}){return <article className={styles.card}><Link href={`/outfits/${outfitSlug(outfit)}`}><div><Image src={`https://picsum.photos/seed/cpo${outfit.id}/600/750`} alt={`${outfit.celebrity} ${outfit.occasion} look`} fill sizes="(max-width:520px) 50vw, 25vw"/><span>{dateFmt.format(new Date(`${outfit.date}T00:00:00`))}</span><b>−{saving(outfit)}%</b></div><section><h3>{outfit.celebrity}</h3><p>{outfit.event}</p><span><s>{inr.format(outfit.worn)}</s><b>{inr.format(outfit.swap)}</b></span></section></Link><button type="button" aria-pressed={saved} onClick={onSave}>{saved?"♥":"♡"}</button></article>;}
