"use client";
import Image from "next/image";
import Link from "next/link";
import {useMemo,useState} from "react";
import { occasionSlug, outfitSlug } from "@/lib/slugs";
import { useSavedList } from "@/lib/saved";
import { outfitPhoto, pricing } from "@/lib/types";
import type { Outfit } from "@/lib/types";
import type { OccasionView } from "@/lib/archive";
import { bandComposition, budgetTiers } from "@/lib/archive";
import styles from "@/app/occasions/[slug]/occasion-detail.module.css";

type SortMode="new"|"saving"|"cheap";
const inr=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
const dateFmt=new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"});
function saving(outfit:Outfit){return outfit.worn>0?Math.round((1-outfit.swap/outfit.worn)*100):0;}
/** "an airport look", not "a airport look". */
const article=(word:string)=>/^[aeiou]/i.test(word)?"an":"a";
function formatDay(value:string|null|undefined){return value?dateFmt.format(new Date(`${value}T00:00:00`)):null;}

/** The date box opens on the occasion's own next date when one is set, and
 *  otherwise two months out — never on a day hardcoded in this file. */
function defaultEventDate(nextDate?:string){
  if(nextDate&&Date.parse(`${nextDate}T00:00:00`)>Date.now())return nextDate;
  return new Date(Date.now()+60*86400000).toISOString().slice(0,10);
}

export function OccasionDetail({occasion,outfits,related}:{occasion:OccasionView;outfits:Outfit[];related:OccasionView[]}){
  const stats=occasion.stats;
  const [eventDate,setEventDate]=useState(()=>defaultEventDate(occasion.nextDate));
  const [budget,setBudget]=useState<number|null>(null);const [sort,setSort]=useState<SortMode>("new");const saved=useSavedList("looks");
  const verdict=useMemo(()=>deliveryVerdict(eventDate),[eventDate]);
  const results=useMemo(()=>outfits.filter((outfit)=>!budget||outfit.swap<=budget).sort((a,b)=>sort==="saving"?(b.worn-b.swap)-(a.worn-a.swap):sort==="cheap"?a.swap-b.swap:b.date.localeCompare(a.date)),[budget,outfits,sort]);
  // The bands, their counts and what sits inside each are all read off this
  // occasion's own looks; the page used to quote three fixed caps and three
  // fixed tallies whatever the archive held.
  const bands=useMemo(()=>budgetTiers(outfits).map((tier)=>({...tier,pieces:bandComposition(outfits,tier.cap)})),[outfits]);
  const checked=formatDay(stats.lastChecked);
  const photo=(index=0)=>stats.photos[index]??stats.photos[0]??`https://picsum.photos/seed/cpocc${occasion.id}/1600/700`;
  const looksLabel=`${stats.looks} ${stats.looks===1?"look":"looks"}`;
  return <main className={styles.page}>
    <header className={styles.hero}><Image src={photo()} alt="" fill priority sizes="100vw"/><div className={styles.overlay}/><div className={styles.shell}><nav><Link href="/">Home</Link><i>›</i><Link href="/occasions">Occasions</Link><i>›</i><span>{occasion.name}</span></nav><h1>{occasion.name}</h1><p>{occasion.description} {looksLabel} decoded piece by piece — and what each costs without the designer price.</p><div className={styles.heroStats}><div><b>{stats.looks}</b><span>Looks decoded</span></div>{stats.averageWorn!==null?<div><b>{inr.format(stats.averageWorn)}</b><span>Avg as worn</span></div>:null}{stats.averageSwap!==null?<div><b>{inr.format(stats.averageSwap)}</b><span>Avg swap</span></div>:null}{stats.swapFrom!==null?<div><b>{inr.format(stats.swapFrom)}</b><span>Cheapest look</span></div>:null}</div></div></header>
    <div className={styles.shell}>
      <section className={styles.calculator}><div><h2>When&apos;s the {occasion.name.toLowerCase()}?</h2><p>Indian delivery runs 4–9 days, and you&apos;ll want time to try it on and swap sizes. Tell us the date and we&apos;ll calculate your real deadline.</p></div><div className={styles.dateForm}><label>Event date<input type="date" value={eventDate} onChange={(event)=>setEventDate(event.target.value)}/></label></div><div className={`${styles.verdict} ${styles[verdict.tone]}`}><strong>{verdict.title}</strong><p>{verdict.body}</p><div><span>Event in<b>{verdict.days} days</b></span><span>Order by<b>{verdict.orderBy}</b></span><span>Typical delivery<b>4–9 days</b></span></div></div></section>
      {stats.looks?<section className={styles.section}><SectionHeading eyebrow="The guide" title={`What to actually wear to ${article(occasion.name)} ${occasion.name.toLowerCase()}`}/><div className={styles.guide}><p>{occasion.description} The best version is the one that works for the event itself, not only for the photograph.</p>{stats.garments[0]?<p>Across the {looksLabel} in this archive, <b>{stats.garments[0].name.toLowerCase()}</b> appears most often. The successful versions concentrate detail where it reads clearly and keep the rest of the styling controlled.</p>:null}<blockquote>If you take one thing from this page: <b>choose the outfit for how the event feels and moves, not only for the first photo.</b></blockquote><p>One statement accessory is usually enough. Repeating every jewellery cue from a celebrity look makes the affordable version feel busier, not richer.</p>{stats.averageSaving!==null&&stats.swapFrom!==null?<p>The dupe economics are strong: the average saving across this archive is <b>{stats.averageSaving}%</b>, with complete looks beginning at {inr.format(stats.swapFrom)}.</p>:null}<small>Written by <b>Rabi</b> · Based on {looksLabel}{checked?` · Prices re-checked ${checked}`:""}</small></div></section>:null}
      {stats.garments.length?<section className={styles.section}><SectionHeading eyebrow="The pattern" title={`What ${looksLabel} have in common`} body="Counted across the archive — not an impression, the actual tally."/><div className={styles.patternGrid}><div className={styles.bars}><h3>Garment worn</h3>{stats.garments.map((garment)=><div key={garment.name}><p><span>{garment.name}</span><b>{garment.count} {garment.count===1?"piece":"pieces"} · {Math.round(garment.count/stats.pieces*100)}%</b></p><i><b style={{width:`${garment.count/stats.garments[0].count*100}%`}}/></i></div>)}</div><div className={styles.panel}>{occasion.colours.length?<section><h3>Colours that dominate</h3><div className={styles.palette}>{occasion.colours.map((colour)=><span key={colour.name}><i style={{background:colour.value}}/><small>{colour.name}</small></span>)}</div></section>:null}{stats.wornBrands.length?<section><h3>Most repeated labels</h3><p className={styles.tags}>{stats.wornBrands.map((brand)=><span key={brand}>{brand}</span>)}</p></section>:null}{stats.swapBrands.length?<section><h3>Where the swaps come from</h3><p className={styles.tags}>{stats.swapBrands.map((brand)=><span key={brand}>{brand}</span>)}</p></section>:null}</div></div></section>:null}
      {bands.length?<section className={styles.section}><SectionHeading eyebrow="By budget" title={`What ${article(occasion.name)} ${occasion.name.toLowerCase()} look costs`} body="Complete looks grouped by what you'd actually spend."/><div className={styles.budgetBands}>{bands.map((band)=><article key={band.cap}><p>Complete look under</p><h3>{inr.format(band.cap)}</h3><span>{band.looks} {band.looks===1?"look":"looks"} in this band</span><ul>{band.pieces.map((piece)=><li key={piece.name}>{piece.name} <b>{inr.format(piece.price)}</b></li>)}</ul><button type="button" onClick={()=>setBudget(band.cap)}>See looks →</button></article>)}</div></section>:null}
      <section className={styles.section}><SectionHeading eyebrow="The archive" title={`All ${looksLabel}`}/><div className={styles.archiveBar}><div>{[null,...bands.map((band)=>band.cap)].map((cap)=><button type="button" aria-pressed={budget===cap} onClick={()=>setBudget(cap)} key={cap??"all"}>{cap?`Under ${inr.format(cap)}`:"All"}</button>)}</div><select value={sort} onChange={(event)=>setSort(event.target.value as SortMode)}><option value="new">Newest</option><option value="saving">Biggest saving</option><option value="cheap">Cheapest swap</option></select></div>{results.length?<div className={styles.grid}>{results.map((outfit)=><OutfitCard outfit={outfit} saved={saved.has(outfitSlug(outfit))} onSave={()=>saved.toggle(outfitSlug(outfit))} key={outfit.id}/>)}</div>:<div className={styles.empty}><h3>{budget?`Nothing under ${inr.format(budget)} yet`:"Nothing decoded here yet"}</h3><p>Looks published in the panel appear here the moment they are saved.</p>{budget&&<button type="button" onClick={()=>setBudget(null)}>Show all</button>}</div>}</section>
      <section className={`${styles.section} ${styles.faq}`}><SectionHeading eyebrow="Asked a lot" title={`${occasion.name} questions`}/>{stats.garments.length?<details open><summary>What should a guest wear?</summary><p>Start with {stats.garments[0].name.toLowerCase()}{stats.garments[1]?` or ${stats.garments[1].name.toLowerCase()}`:""}, then tune the fabric weight and jewellery to the time of day and how much movement the event involves.</p></details>:null}{stats.averageWorn!==null&&stats.averageSwap!==null?<details><summary>How much should the complete outfit cost?</summary><p>The celebrity looks average {inr.format(stats.averageWorn)}, while the swaps average {inr.format(stats.averageSwap)}.{stats.swapFrom!==null?` A convincing complete look can start around ${inr.format(stats.swapFrom)}.`:""}</p></details>:null}{occasion.colours.length?<details><summary>Which colours work best?</summary><p>{occasion.colours.map((colour)=>colour.name).join(", ")} recur most often across the archive. Use one as the dominant colour and keep accessories quieter.</p></details>:null}<details><summary>How early should I order?</summary><p>Three weeks is comfortable. Two weeks is tight but workable. Inside ten days, prioritize in-stock items with express delivery.</p></details></section>
      {related.length?<section className={styles.related}><SectionHeading eyebrow="Nearby" title={`Other ${occasion.group.toLowerCase()} occasions`}/><div>{related.map((item)=><Link href={`/occasions/${occasionSlug(item)}`} key={item.id}><Image src={item.stats.photos[0]??`https://picsum.photos/seed/cpocc${item.id}/600/400`} alt="" fill sizes="(max-width:1023px) 50vw, 25vw"/><span><b>{item.name}</b><small>{item.stats.looks} looks{item.stats.swapFrom!==null?` · from ${inr.format(item.stats.swapFrom)}`:""}</small></span></Link>)}</div></section>:null}
    </div>
  </main>;
}

/** Counted from today, so the deadline is real every day the page is read. */
function deliveryVerdict(value:string){const now=new Date();const event=new Date(`${value}T00:00:00`);const days=Math.round((event.getTime()-now.getTime())/86400000);const order=new Date(event.getTime()-14*86400000);const orderBy=Number.isNaN(order.getTime())?"Choose a date":dateFmt.format(order);if(Number.isNaN(days))return{tone:"bad",title:"Choose a date",body:"Pick the day of the event and we'll work backwards from it.",days:0,orderBy};if(days<0)return{tone:"bad",title:"That date has passed",body:"Pick a future date and we'll work backwards from it.",days:0,orderBy};if(days>=28)return{tone:"ok",title:"You have plenty of time",body:`Order by ${orderBy} and you'll have room to try things on and exchange a size.`,days,orderBy};if(days>=14)return{tone:"warn",title:"Getting tight — order this week",body:"You have delivery time, but limited room for a size exchange.",days,orderBy};return{tone:"bad",title:"Express delivery or local shopping",body:"You are inside the comfortable online-ordering window.",days:Math.max(days,0),orderBy};}
function SectionHeading({eyebrow,title,body}:{eyebrow:string;title:string;body?:string}){return <div className={styles.sectionHeading}><p>{eyebrow}</p><h2>{title}</h2>{body&&<span>{body}</span>}</div>;}
function OutfitCard({outfit,saved,onSave}:{outfit:Outfit;saved:boolean;onSave:()=>void}){const money=pricing(outfit);return <article className={styles.card}><Link href={`/outfits/${outfitSlug(outfit)}`}><div><Image src={outfitPhoto(outfit)?.url ?? `https://picsum.photos/seed/cpo${outfit.id}/600/750`} alt={`${outfit.celebrity} ${outfit.occasion} look`} fill sizes="(max-width:520px) 50vw, 25vw"/><span>{dateFmt.format(new Date(`${outfit.date}T00:00:00`))}</span><b>−{saving(outfit)}%</b></div><section><h3>{outfit.celebrity}</h3><p>{outfit.event}</p><span><s>{inr.format(money.wornTotal)}</s>{money.anySwapped?<b>{inr.format(money.swapTotal)}</b>:null}</span></section></Link><button type="button" aria-pressed={saved} onClick={onSave}>{saved?"♥":"♡"}</button></article>;}
